"""initial_version

Revision ID: 633e2e77a9f3
Revises: 
Create Date: 2024-06-21 20:15:37.444059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '633e2e77a9f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mobile_no', sa.VARCHAR(length=250), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='user_auth_email_key'),
    schema='recipe_db'
    )
    op.create_index(op.f('ix_recipe_db_users_id'), 'users', ['id'], unique=False, schema='recipe_db')
    op.create_index('users_email', 'users', ['email'], unique=False, schema='recipe_db')
    op.create_index('users_mobile_no', 'users', ['mobile_no'], unique=False, schema='recipe_db')
    op.create_table('recipe',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default='{}'),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['recipe_db.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recipe_db'
    )
    op.create_index(op.f('ix_recipe_db_recipe_id'), 'recipe', ['id'], unique=False, schema='recipe_db')
    op.create_index('recipe_name', 'recipe', ['name'], unique=False, schema='recipe_db')
    op.create_index('recipe_title', 'recipe', ['title'], unique=False, schema='recipe_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recipe_title', table_name='recipe', schema='recipe_db')
    op.drop_index('recipe_name', table_name='recipe', schema='recipe_db')
    op.drop_index(op.f('ix_recipe_db_recipe_id'), table_name='recipe', schema='recipe_db')
    op.drop_table('recipe', schema='recipe_db')
    op.drop_index('users_mobile_no', table_name='users', schema='recipe_db')
    op.drop_index('users_email', table_name='users', schema='recipe_db')
    op.drop_index(op.f('ix_recipe_db_users_id'), table_name='users', schema='recipe_db')
    op.drop_table('users', schema='recipe_db')
    # ### end Alembic commands ###
